# Gruvbox Material Medium Dark

[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black   = "#3c3836"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#504945"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#ddc7a1"

# error on alacritty 0.13
#[colors.indexed_colors]
# optional extra colors sometimes used by gruvbox-material
#indexed_colors = [
#  { index = 16, color = "#e78a4e" },
#  { index = 17, color = "#c14a4a" }
#]
