name: Run docker.sh

on:
  push:
    branches:
      - main
      - '*'
  workflow_dispatch:  # Allows manually triggering the workflow

permissions:
  contents: read  # Grants read access to repository content

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker.sh
        run: |
          chmod +x utils/ubuntu-utility/docker.sh
          ./utils/ubuntu-utility/docker.sh

